//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SslInterfaces
{
    [Serializable]
    public class Float64ArrayMsg : Message
    {
        public const string k_RosMessageName = "ssl_interfaces/Float64Array";
        public override string RosMessageName => k_RosMessageName;

        //  A variably lengthed array of double values.
        //  The array of values.
        public double[] data;

        public Float64ArrayMsg()
        {
            this.data = new double[0];
        }

        public Float64ArrayMsg(double[] data)
        {
            this.data = data;
        }

        public static Float64ArrayMsg Deserialize(MessageDeserializer deserializer) => new Float64ArrayMsg(deserializer);

        private Float64ArrayMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.data, sizeof(double), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.data);
            serializer.Write(this.data);
        }

        public override string ToString()
        {
            return "Float64ArrayMsg: " +
            "\ndata: " + System.String.Join(", ", data.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
